### ISSUE TITLE
Normalisation by measurement time

### ISSUE THREAD

**Issue by WouterGrun** [vivianel/DarePy-SANS#5]
Both the transmission and scattering are currently normalised by the measurement time. This causes issues if the beam went down during a measurement.

It is probably better to normalise against the number of monitors (but which one?)

function
normalization.normalze_time(config, hdf_name, counts)
called in
transmission.normalize_trans(config, result, hdf_name, counts)
correction.load_and_normalize(config, result, name_hdf)

**Comment by vivianel** [comment]
Hi Wouter

I have indeed noticed that some time ago. If you normalize with the monitors, then we should not normalize by time. In the same scrip "normalization", you shuould find "normalize_flux". There we tested some time go, and monitor 2 should be the best for normalization, as it is the one that counts the neutrons as a function of wavelength.
